### ISSUE TITLE
A few minor suggestions for the documentation

### ISSUE THREAD

**Issue by mikaem** [mancellin/capytaine#10]
Just a few friendly suggestions and not blockers for the JOSS paper:

 * Consider adding links to complete problem files [here](https://ancell.in/capytaine/latest/user_manual/cookbook.html#id1). I think these problems are all (?) in the examples directory, but I had to search for them in order to run them. 
 
 * Consider moving class docstrings from `__init__` method to the top of the class. See [cylinders](https://ancell.in/capytaine/latest/developer_manual/api/capytaine.bodies.predefined.cylinders.html). Docstrings are not showing up in the API because they are placed under the `__init__` method. It may only be in the [predefined bodies](https://ancell.in/capytaine/latest/developer_manual/api/capytaine.bodies.predefined.html#submodules) submodule, did not check all.

**Comment by mancellin** [comment]
Thanks, I had not noticed that sphinx was ignoring the docstring of `__init__`.
The published version of the documentation will be updated in a couple of days.
