### ISSUE TITLE
What is proper frequency domain convention for capytaine: exp(iwt) or exp(-iwt)?

### ISSUE THREAD

**Issue by ckesanapalli** [mancellin/capytaine#102]
Hi Guys, 

I am currently performing a floating WEC simulation in the capytaine and trying to compare it with WAMIT results. The added mass, radiation damping, and excitation forces are in good agreement, 

But RAO is not satisfactory when I used the default RAO function in capytaine `capytaine.post_pro.rao`.  

I think this is due to the convention of the equation of motion in the `impedance` function 
https://github.com/mancellin/capytaine/blob/6290cc0378ec769fdaa3220cd11a772793bab93d/capytaine/post_pro/impedance.py#L15

```python
A = (-omega**2*(dataset['mass'] + dataset['added_mass'])
         + 1j*omega*dataset['radiation_damping']
         + dataset['hydrostatic_stiffness'])
```
But when I changed the above code to the following code, the results are in good agreement. 

```python
A = (-omega**2*(dataset['mass'] + dataset['added_mass'])
         - 1j*omega*dataset['radiation_damping']
         + dataset['hydrostatic_stiffness'])
```

I think this due to the frequency domain convention of the NEMOH i.e., `exp(-iwt)`  (as mentioned in [here](https://lheea.ec-nantes.fr/valorisation/logiciels-et-brevets/nemoh-general-notations-and-conventions)) different from WAMIT `exp(iwt)`  (as mentioned in [here](https://www.wamit.com/manualupdate/v74_manual.pdf) pg 3-1). 

Please mention whether I am right or wrong. 

https://github.com/mancellin/capytaine/blob/6290cc0378ec769fdaa3220cd11a772793bab93d/capytaine/post_pro/impedance.py#L58

**Comment by mancellin** [comment]
This has been recently discussed in #41, but has not been fixed yet. If you came to the same conclusion independently, it makes me very confident that this is the right fix.
Thank you for reporting it!

**Comment by ckesanapalli** [comment]
Until the fix, a quick alternative is 

```python
dataset["RAO"] = capytaine.post_pro.rao(dataset, wave_direction=0, 
                                          dissipation=-2*dataset["radiation_damping"])
```
