### ISSUE TITLE
Integration in FreeCAD-Ship

### ISSUE THREAD

**Issue by sanguinariojoe** [mancellin/capytaine#108]
Hey guys!

Just to let you know I am integrating capytaine in FreeCAD (In the FreeCAD-Ship module). You can follow the dev [here](https://github.com/sanguinariojoe/freecad.ship/tree/seakeeping), and get a fancy snapshot [here](https://twitter.com/jlcercos/status/1454104295868096516).

Thanks for this project!

**Comment by RubendeBruin** [comment]
Hi @sanguinariojoe , interesting project. How are you producing a mesh for Capytaine? I think the geometry from FreeCAD is not directly a good mesh.

**Comment by sanguinariojoe** [comment]
No, it is not... But FreeCAD provides a mesher with a default meshing algorithm, as well as gmsh and mefisto backends. The main limitation is that it only works with triangular meshes (yet)

**Comment by RubendeBruin** [comment]
Well, I don't see any issue with triangular meshes.

**Comment by mancellin** [comment]
I'm closing the issue. Feel free to reopen if you have any issue with your project or if you'd like to share more information.
