### ISSUE TITLE
ImportError on green_functions

### ISSUE THREAD

**Issue by MEL29200** [mancellin/capytaine#111]
Hi,
I'm new on Capytaine and I try to use this code for a project about Wave Energy Converter like CETO.
It might be a basic issue but I can't import "Delhommeau_f90" and "XieDelhommeau_f90" from Spyder.
Those files are .PYD, is that a type that need specific actions ?

Whenever I try to import capytaine, I have the following warning about those files :
ImportError: DLL load failed: The specified module could not be found.

Yet they are in my folder under the right name, and I can import the following modules : 
capytaine.__about__
capytaine.meshes
capytaine.bodies
capytaine.bem
capytaine.green_functions
capytaine.tools.prony_decomposition
capytaine.green_functions.abstract_green_function

Could anyone help me please ?

Thanks a lot

**Comment by mancellin** [comment]
These modules are Fortran routines that need to be compiled.
The `conda` packages include the compiled code for several platforms, so installing Capytaine with `conda` is the simplest way to get them.

**Comment by MEL29200** [comment]
I did install Capytaine with :
**conda install -c conda-forge capytaine** on Anaconda Prompt
Is that what you meant ?

**Comment by mancellin** [comment]
Yes. If it is not working, then it is a bug, the Green function modules should be there.
Could you tell me more about your operating system, your version of Python and the version of the Capytaine package that was installed (`conda list capytaine`)?

**Comment by MEL29200** [comment]
I'm working on **Windows 10 (64bits)**, with **Python 3.8.8** and the **version 1.3 of Capytaine**
The strangest part is that I can see the modules. It was first named with a _cp38-win_amd64_ extension so I copied and renamed them without extension but it still does not work.

![image](https://user-images.githubusercontent.com/94049296/141127830-4fdcd979-d6ce-496d-8ed3-6901e4ff5868.png)

**Comment by mancellin** [comment]
I guess this is the same issue as the one reported in https://github.com/mancellin/capytaine/issues/1#issuecomment-881362158

**Comment by mancellin** [comment]
@MEL29200 Would using the Windows Subsystem for Linux be a possible workaround for you?

**Comment by MEL29200** [comment]
Yes it seems I'm not the only one.
It should be possible next week, using another computer.
I'll try and let you know if this works.
Thank you for your help so far :)

**Comment by RubendeBruin** [comment]
this is an error that also pops up when there is a conflict in environments or the path are not set correctly.
Can you import numpy?

**Comment by MEL29200** [comment]
Yes I can import numpy.
How can I check path settings or environment conflicts ?

**Comment by RubendeBruin** [comment]
the easiest is from python:

```python
import os
for p in os.environ['Path'].split(';'):
    print(p)
```

and 

```python
import sys
for p in sys.path:
    print(p)
```

One of the things that can go wrong is that an incompatible .dll is located in one of the higher priority paths. When python or the module tries to load that dependency then the whole thing fails.

Can you try to import Delhommeau_f90 directly? Ie:

`import Delhommeau_f90`

and if that fails with a module-not-found, then add its path using

`sys.path.append(r'c:\#.pyd location#')`

and try again

**Comment by MEL29200** [comment]
Thank you, I added the **.pyd location** as you suggested but the ImportError still occurs.
`ImportError: Dll Load Failed: The specified module could not be found`

To recap : 
- My _capytaine_ folder is in **C:\Users\manteame\Desktop\capytaine**
- I added this path with `sys.path.append(r'C:\Users\manteame\Desktop\capytaine')` 
- I work on this specific folder in Python : 
![image](https://user-images.githubusercontent.com/94049296/143446322-2f3f7448-5037-4f8d-b45b-c20a3b139d00.png)
And the ImportError popped-up when I tried ` import Delhommeau_f90`

I did the same thing with **C:\Users\manteame\Desktop\capytaine\green_functions** where the .pyd files are, as you said.
But the ImportError keeps popping.

**Comment by RubendeBruin** [comment]
I'm not really sure what the work-folder in spyder does.

When I do `from capytaine.green_functions import Delhommeau_f90` in a python session and I look at the modules that get loaded using ProcessExplorer then I get a huge list, but the most likely candidates are:

<img width="985" alt="image" src="https://user-images.githubusercontent.com/34062862/143463305-ceb528b2-f5af-452b-bce9-d37bde50e715.png">

I think the first suspects are the fortran support files,
can you check if you have:

- `miniconda3\envs\work\Library\bin\libifcoremd.dll`
- `miniconda3\envs\work\Library\mingw-w64\bin\libgfortran-3.dll`

where envs\work is the conda environment in which I installed capytaine. If you did not install in a separate environment then remove the envs\work part of the paths:

- `miniconda3\Library\bin\libifcoremd.dll`
- `miniconda3\Library\mingw-w64\bin\libgfortran-3.dll`

**Comment by MEL29200** [comment]
Yes I do have both **libifcoremd.dll** and **libgfortran-3.dll**

**Comment by RubendeBruin** [comment]
I have just created an isolated conda environment and installed only capytaine it.
On my pc (windows 10, x64, python 3.8) it all works and all the dlls that get loaded are either in that environment (were installed when I installed capytaine) or in windows/system32.

Conda list gives me:

```
# packages in environment at c:\python\miniconda3\envs\cap:
#
# Name                    Version                   Build  Channel
ca-certificates           2021.10.8            h5b45459_0    conda-forge
capytaine                 1.3              py38h90da266_1    conda-forge
importlib-metadata        4.8.2            py38haa244fe_0    conda-forge
importlib_metadata        4.8.2                hd8ed1ab_0    conda-forge
intel-openmp              2021.4.0          h57928b3_3556    conda-forge
libblas                   3.9.0              12_win64_mkl    conda-forge
libcblas                  3.9.0              12_win64_mkl    conda-forge
libflang                  5.0.0           h6538335_20180525    conda-forge
liblapack                 3.9.0              12_win64_mkl    conda-forge
llvm-meta                 5.0.0                         0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mkl                       2021.4.0           h0e2418a_729    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
numpy                     1.21.4           py38h089cfbf_0    conda-forge
openmp                    5.0.0                    vc14_1    conda-forge
openssl                   3.0.0                h8ffe710_2    conda-forge
pandas                    1.3.4            py38h5d928e2_1    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
python                    3.8.12          h900ac77_2_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
scipy                     1.7.3            py38ha1292f7_0    conda-forge
setuptools                59.2.0           py38haa244fe_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.36.0               h8ffe710_2    conda-forge
tbb                       2021.4.0             h2d74725_1    conda-forge
typing_extensions         4.0.0              pyha770c72_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xarray                    0.20.1             pyhd8ed1ab_0    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
```


Can you create a fresh capytaine environment from the anaconda-prompt (not in spyder) and see if that works for you:

- `conda create --name cap python=3.8`
- `conda activate cap`
- `conda install capytaine -c conda-forge`
- `python` (start python console)
- `from capytaine.green_functions import Delhommeau_f90 `

**Comment by MEL29200** [comment]
That seems to work ! I don't have any error popping
Do you have any idea where the problem comes from with this ?
Will I be able to work with my scipts in Spyder ?

**Comment by RubendeBruin** [comment]
hi @MEL29200 , good to hear that things are working.

We should be able to get this working in spyder. The trick is to let spyder use the environment with capytaine in it.

Try the following:
In spyder
![image](https://user-images.githubusercontent.com/34062862/143891376-3c57171f-0c00-4a58-9d09-cc7189fb874b.png)

<img width="402" alt="image" src="https://user-images.githubusercontent.com/34062862/143891653-4a695c5f-506e-4d75-9133-2aba79cbb283.png">


<img width="220" alt="image" src="https://user-images.githubusercontent.com/34062862/143891423-00d44881-2ed1-4191-9f65-3f02d62314d2.png">



<img width="572" alt="image" src="https://user-images.githubusercontent.com/34062862/143891601-9fd148d0-ff55-42dc-9e8f-db3f3e5e7569.png">

**Comment by MEL29200** [comment]
When I try : 
`import numpy`

I have :

```
Traceback (most recent call last):

  File "C:\APPLIS\Anaconda3\envs\cap\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray

  File "C:\APPLIS\Anaconda3\envs\cap\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides

  File "C:\APPLIS\Anaconda3\envs\cap\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (

ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\manteame\AppData\Local\Temp/ipykernel_82068/2172125874.py", line 1, in <module>
    import numpy

  File "C:\APPLIS\Anaconda3\envs\cap\lib\site-packages\numpy\__init__.py", line 150, in <module>
    from . import core

  File "C:\APPLIS\Anaconda3\envs\cap\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "C:\APPLIS\Anaconda3\envs\cap\pythonw.exe"
  * The NumPy version is: "1.21.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.
```

I tried reading advices in the link but I didn't find what is wrong

**Comment by RubendeBruin** [comment]
Probably: 

<img width="690" alt="image" src="https://user-images.githubusercontent.com/34062862/144035443-f18671ce-001e-42a4-a6e5-5714e2fe575d.png">

can you copy the output?

**Comment by MEL29200** [comment]
```
import os
for p in os.environ['Path'].split(';'):
    print(p)
```
Gives : 
 
C:\APPLIS\WPy64-3760\python-3.7.6.amd64\lib\site-packages\PyQt5\Qt\bin
C:\APPLIS\WPy64-3760\python-3.7.6.amd64\lib\site-packages\numpy\DLLs
C:\APPLIS\WPy64-3760\python-3.7.6.amd64\lib\site-packages\pywin32_system32
C:\APPLIS\WPy64-3760\python-3.7.6.amd64\Lib\site-packages\PyQt5
C:\APPLIS\WPy64-3760\python-3.7.6.amd64\Lib\site-packages\PySide2
C:\APPLIS\WPy64-3760\python-3.7.6.amd64\
C:\APPLIS\WPy64-3760\python-3.7.6.amd64\DLLs
C:\APPLIS\WPy64-3760\python-3.7.6.amd64\Scripts
C:\APPLIS\WPy64-3760\python-3.7.6.amd64\..\t
C:\APPLIS\WPy64-3760\python-3.7.6.amd64\..\t\mingw32\bin
C:\APPLIS\WPy64-3760\python-3.7.6.amd64\..\t\R\bin\x64
C:\APPLIS\WPy64-3760\python-3.7.6.amd64\..\t\Julia\bin
C:\APPLIS\WPy64-3760\python-3.7.6.amd64\..\n
C:\APPLIS\SIMULIA\Commands
C:\Program Files\Microsoft MPI\Bin\
C:\Perl64\site\bin
C:\Perl64\bin
C:\APPLIS\AMESIM\2020.2\Amesim
C:\APPLIS\AMESIM\2020.2\Amesim\win64
C:\APPLIS\AMESIM\2020.2\Amesim\win32
C:\APPLIS\AMESIM\2020.2\Amesim\sys\mingw32\bin
C:\APPLIS\AMESIM\2020.2\Amesim\sys\python\win64
C:\APPLIS\AMESIM\2020.2\System Architect\win64
C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\mpirt
C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32_win\mpirt
C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler
C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32_win\compiler
C:\Program Files (x86)\Common Files\Oracle\Java\javapath
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\Program Files\PuTTY\
C:\Program Files (x86)\LyX 2.3\Perl\bin
C:\Program Files\MiKTeX 2.9\miktex\bin\x64\
C:\Program Files\Microsoft SQL Server\120\Tools\Binn\
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
C:\Program Files\MATLAB\R2020b\runtime\win64
C:\Program Files\MATLAB\R2020b\bin
C:\TELEMAC\V6P1\bin
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
C:\TELEMAC\Pre_Post\bi
C:\Users\manteame\AppData\Local\Microsoft\WindowsApps


```
import sys
for p in sys.path:
    print(p)
```


Gives :

U:\.spyder_win
U:\PROJET SIT (CETO)
C:\APPLIS\Anaconda3\envs\cap\python38.zip
C:\APPLIS\Anaconda3\envs\cap\DLLs
C:\APPLIS\Anaconda3\envs\cap\lib
C:\APPLIS\Anaconda3\envs\cap
C:\APPLIS\Anaconda3\envs\cap\lib\site-packages
C:\APPLIS\Anaconda3\envs\cap\lib\site-packages\win32
C:\APPLIS\Anaconda3\envs\cap\lib\site-packages\win32\lib
C:\APPLIS\Anaconda3\envs\cap\lib\site-packages\Pythonwin
C:\APPLIS\Anaconda3\envs\cap\lib\site-packages\IPython\extensions
C:\Users\manteame\.ipython

**Comment by RubendeBruin** [comment]
Ok, I'm pretty sure that these paths:

`C:\APPLIS\WPy64-3760\python-3.7.6.amd64\......`

mess up your imports.

They probably contains dlls with the same name but for a different python version.

Can you remove those paths (without breaking other software)? They should be in your system or user environment variables.

**Comment by MEL29200** [comment]
When I try something like  :
`os.environ['Path'].split(';').remove('C:\\APPLIS\\WPy64-3760\\python-3.7.6.amd64\\lib\\site-packages\\PyQt5\\Qt\\bin')`

It does remove the path, what am I doing wrong ?

**Comment by RubendeBruin** [comment]
os.environ['Path'] gives a string
.split(';') then *creates* a list by splitting the string
.remove then removes one of the entries from *that* list

But that list is not the path. The path is the string, and the string is untouched. So this does not do anything.

I think the easiest is to remove the complete path just to test if it works.

`os.environ['Path'] = ''` could do the trick, although I'm not sure.

But let's first give that a go to see if it works

**Comment by MEL29200** [comment]
Thank you for your explanations.

With
`os.environ['Path'] = ''`
The ImportError keeps popping up.

**Comment by RubendeBruin** [comment]
Ok, too bad. Then we have to dig a bit deeper.

when you activate 'cap' and then start python from the command prompt then it did work, right?

**Comment by mancellin** [comment]
> os.environ['Path'] = '' could do the trick, although I'm not sure

Some environment variables are read at startup, so changing them on the fly while Python is running might not have any effect (see #47).
On the other hand, I don't believe that Python uses the OS path to load libraries anyway (only the `PYTHONPATH` stored in `sys.path`).

**Comment by RubendeBruin** [comment]
Hi @mancellin , its not only python modules. Its also compiled extensions (numpy) that load dynamic libraries. I think they do not care about the python-path too much.

@MEL29200 
1. Can you check what your paths are when it does work?

2. Can you start spyder from the command prompt after activating cap ? Does that help?

**Comment by MEL29200** [comment]
`os.environ['Path'].split(';') `

Gives :

[
'C:\\APPLIS\\Anaconda3\\envs\\cap'
'C:\\APPLIS\\Anaconda3\\envs\\cap\\Library\\mingw-w64\\bin',
'C:\\APPLIS\\Anaconda3\\envs\\cap\\Library\\usr\\bin'
'C:\\APPLIS\\Anaconda3\\envs\\cap\\Library\\bin'
'C:\\APPLIS\\Anaconda3\\envs\\cap\\Scripts',
'C:\\APPLIS\\Anaconda3\\envs\\cap\\bin'
'C:\\APPLIS\\Anaconda3\\condabin',
'C:\\APPLIS\\SIMULIA\\Commands'
'C:\\Program Files\\Microsoft MPI\\Bin'
'C:\\Perl64\\site\\bin', 'C:\\Perl64\\bin'
'C:\\APPLIS\\AMESIM\\2020.2\\Amesim'
'C:\\APPLIS\\AMESIM\\2020.2\\Amesim\\win64'
'C:\\APPLIS\\AMESIM\\2020.2\\Amesim\\win32'
'C:\\APPLIS\\AMESIM\\2020.2\\Amesim\\sys\\mingw32\\bin'
'C:\\APPLIS\\AMESIM\\2020.2\\Amesim\\sys\\python\\win64'
'C:\\APPLIS\\AMESIM\\2020.2\\System Architect\\win64'
'C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64_win\\mpirt'
'C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\ia32_win\\mpirt'
'C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64_win\\compiler'
'C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\ia32_win\\compiler'
'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath'
'C:\\WINDOWS\\system32'
'C:\\WINDOWS'
'C:\\WINDOWS\\System32\\Wbem'
'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0'
'C:\\WINDOWS\\System32\\OpenSSH'
'C:\\Program Files\\PuTTY'
'C:\\Program Files (x86)\\LyX 2.3\\Perl\\bin'
 'C:\\Program Files\\MiKTeX 2.9\\miktex\\bin\\x64'
'C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn'
'C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit'
'C:\\Program Files\\MATLAB\\R2020b\\runtime\\win64'
'C:\\Program Files\\MATLAB\\R2020b\\bin'
'C:\\TELEMAC\\V6P1\\bin'
'C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL'
'C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL'
'C:\\TELEMAC\\Pre_Post\\bi'
'C:\\Users\\manteame\\AppData\\Local\\Microsoft\\WindowsApps'
'.'
]

**Comment by MEL29200** [comment]
Ok, I installed Spyder on **cap** and open it in Anaconda Prompt and that seems to work, finally !
Thank you very much to both of you for your help and the time you spent on this :D

**Comment by RubendeBruin** [comment]
glad you got it working!

I think that you installed spyder previously via WinPython and WinPython probably adds the `C:\APPLIS\WPy64-3760\python-3.7.6.amd64\lib\site-packages\PyQt5\Qt\bin` paths when launching spyder. Guess that is what breaks things.

**Comment by mancellin** [comment]
I'm not sure there is anything to be done in Capytaine on this topic. I'm closing the issue, feel free to reopen if needed.
