### ISSUE TITLE
PyPI package broken

### ISSUE THREAD

**Issue by cmichelenstrofer** [mancellin/capytaine#112]
Currently `pip install capytaine` does not work unless you already have installed `numpy`. The problem is that although `numpy` is listed under `install_requires` in `setup.py`, it is used in that same file (`from numpy.distutils.core import Extension, setup`). 

I think the solution from the [second answer here](https://stackoverflow.com/questions/19919905/how-to-bootstrap-numpy-installation-in-setup-py) should work. 

It would look something like:
```python
from setuptools import dist
dist.Distribution().fetch_build_eggs(['numpy'])
```

**Comment by mancellin** [comment]
Interesting, thank you. I'll test that in the next release.

I guess it would solve #76 @RubendeBruin

**Comment by RubendeBruin** [comment]
@mancellin , Guess it could, but then well see if readthedocs has a fortran compiler. Definitely worth a try
