### ISSUE TITLE
Capytaine Results Files Show Zeroes Only

### ISSUE THREAD

**Issue by ccz359** [mancellin/capytaine#125]
Hello @mancellin

I have a project where I am using the Sandia Labs RM3 Wec-Sim model to kickstart an analysis on my own design. I have used their code for Capytaine, but made some modifications including the mesh input files. One other modification I made was to the call_capytaine.py file following the GitHub meshmagick Issue 19 solution. I am able to run WP.py without errors and it generates a result file, however it is full of zeroes. 

I've checked both meshes with healmesh -hm in meshmagick for both the spar and float meshes, and all appears fine. I did run the RM3 code first in Capytaine before applying changes, and it successfully produced results. 

I am using Windows, Python 3.9, conda 4.11.0. I've attached my working folder.

Do you know why my results may be producing only zeroes? Any insight would be appreciated.

Thanks!
[WP.zip](https://github.com/mancellin/capytaine/files/7943645/WP.zip)

**Comment by mancellin** [comment]
Hi,

Which files are you talking about?

If you are worried about the `KH_0.dat` files, it seems to me that currently you don't do anything with the `khs`variable:
```python
khs = np.zeros((3,3))
# [...]
# Write hydrostatic stiffness to KH.dat file as 
khs_full = np.zeros((6,6))
khs_full[2:5, 2:5] += khs
tmp = savepath + 'KH' + fileind +'.dat'
np.savetxt(tmp, khs_full)
```

**Comment by ccz359** [comment]
Thanks for the reply, and for all your hard work on Capytaine. I was able to successfully run Capytaine on my design last week. Thanks again!
