### ISSUE TITLE
zero-size array to reduction operation maximum which has no identity when importing stl file

### ISSUE THREAD

**Issue by soffalonsoo** [mancellin/capytaine#128]
```
result = solver.solve(problem)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [32], in <cell line: 1>()
----> 1 result = solver.solve(problem)

File ~/opt/anaconda3/envs/pearl/lib/python3.10/site-packages/capytaine/bem/solver.py:80, in BEMSolver.solve(self, problem, keep_details)
     63 """Solve the linear potential flow problem.
     64 
     65 Parameters
   (...)
     76     an object storing the problem data and its results
     77 """
     78 LOG.info("Solve %s.", problem)
---> 80 if problem.wavelength < 8*problem.body.mesh.faces_radiuses.max():
     81     LOG.warning(f"Resolution of the mesh (8×max_radius={8*problem.body.mesh.faces_radiuses.max():.2e}) "
     82                 f"might be insufficient for this wavelength (wavelength={problem.wavelength:.2e})!")
     84 S, K = self.engine.build_matrices(
     85     problem.body.mesh, problem.body.mesh,
     86     problem.free_surface, problem.sea_bottom, problem.wavenumber,
     87     self.green_function
     88 )

File ~/opt/anaconda3/envs/pearl/lib/python3.10/site-packages/numpy/core/_methods.py:40, in _amax(a, axis, out, keepdims, initial, where)
     38 def _amax(a, axis=None, out=None, keepdims=False,
     39           initial=_NoValue, where=True):
---> 40     return umr_maximum(a, axis, None, out, keepdims, initial, where)

ValueError: zero-size array to reduction operation maximum which has no identity
```

**Comment by mancellin** [comment]
The error message seems to suggest that the mesh has no face.
Could be a bug in the STL file import.
Would you mind providing some more details on your mesh?

**Comment by soffalonsoo** [comment]
if I do body.show() I can see the object. I have tried Binary and ASCII when converting it to an stl file.
<img width="494" alt="Captura de pantalla 2022-03-14 a las 9 58 50" src="https://user-images.githubusercontent.com/90805431/158187352-1123ae39-ff57-4f2d-9eae-60944d063fbc.png">
This is a mesh created with mesh- polygon mesh primitives- cylinder- 50 vertical faces- 50 round faces with rhino (this is triangular, I have also tried quad meshing tough and get the same error). Is there an attribute in the mesh class that would enable to get more mesh info directly from capytaine?

**Comment by soffalonsoo** [comment]
import logging
import numpy as np
import capytaine as cpt
import vtk
import matplotlib
from capytaine.post_pro import rao

top_float = FloatingBody.from_file('/Users/sofia/Desktop/PEARL/vertical_cylinder.stl')
top_float.show()


# Automatically add the six degrees of freedom of a rigid body
top_float.add_all_rigid_body_dofs()
top_float.keep_immersed_part()
#top_float.add_translation_dof(name="Heave")


omega_range = np.linspace(0.1, 6.0, 5)
dof = "Heave"
problems = [
    cpt.RadiationProblem(body=top_float, radiating_dof=dof, omega=omega, rho=rho_sw)
    for dof in top_float.dofs
    for omega in omega_range
]
top_float.show()
# Water density, gravity and water depth have not been specified.
# Default values are used.

###################
## Solve problem ##
###################
# This uses BEMSolver to solve the problem(s) generated above

# Solve all radiation problems
#solver = cpt.BEMSolver()
direct_linear_solver = cpt.BasicMatrixEngine(linear_solver='direct')
solver = cpt.BEMSolver(engine=direct_linear_solver)
results = [solver.solve(pb) for pb in sorted(problems)]






# Gather the computed added mass into a labelled array.
data = cpt.assemble_dataset(results)

##################
## Plot results ##
# Plot the added mass of each dofs as a function of the frequency
import matplotlib.pyplot as plt
plt.figure()
for dof in top_float.dofs:
    plt.plot(
        omega_range,
        data['added_mass'].sel(radiating_dof=dof, influenced_dof=dof),
        label=dof,
        marker='o',
    )
plt.xlabel('omega')
plt.ylabel('added mass')
plt.legend()
plt.tight_layout()
plt.show()
##################
# This plots the results of the added mass computation

#print(data['radiation_damping'].sel(radiating_dof=dof, influenced_dof=dof))
print(f"RAO=====>{data['radiation_damping'].sel(radiating_dof=dof, influenced_dof=dof)}")
print("solved")

**Comment by mancellin** [comment]
> From the image it seems like it is not immersed but I'm using the top_float.keep_immersed_part() command

When you are using that command, all the panels above the free surface are removed, so you might have nothing left.
What if you add something like
```
top_float.translate_z(-5.0)
```
before the `keep_immersed_part()`?

**Comment by mancellin** [comment]
Was that the issue?
If so, there should be a better error message in this case, I'll add that to my todo list.

**Comment by soffalonsoo** [comment]
Yea!! Thank you very much for your help!
