### ISSUE TITLE
Problem displaying mesh/animation

### ISSUE THREAD

**Issue by sitadrost** [mancellin/capytaine#17]
Just installed Capytaine through conda, on Scientific Linux 7. The step-by-step example runs fine from Spyder, except that I can't view the mesh. Up to now, I've seen two types of behaviour: 
1. sphere.show() opens Mesh Viewer in a new window, but then nothing is shown and Mesh Viewer and the IPython console seem to freeze
2. sphere.show() opens Mesh Viewer in a new window, but then this window crashes, together with the IPython console

The same happens with the animation from the Cookbook example "Animated free surface elevation". Has anyone experienced the same issue? Is there a way to fix this?

**Comment by mancellin** [comment]
Hi @sitadrost,
The problem probably comes from the VTK library used by Capytaine for 3D display.
Could you try running some simple VTK script, such as [this one](https://lorensen.github.io/VTKExamples/site/Python/GeometricObjects/CylinderExample/)?
If it fails in the same way, you'll have to look for a problem in your installation of VTK, OpenGL or your graphics drivers...

**Comment by sitadrost** [comment]
Hi Matthieu,
Thanks for getting back, you're fast! I'll try testing with a simple VTK script on Monday, when I'm back in the office.

**Comment by sitadrost** [comment]
You were right, running that script results in the same behaviour: a new window opens, and then nothing happens until I restart the kernel. I'll check my installations of VTK, OpenGL etc. 
I haven't experienced any trouble with VTK, OpenGL or graphics drivers using ParaView though. Does Capytaine use its own VTK and OpenGL?

**Comment by sitadrost** [comment]
Ah wait, sorry, I was too quick: after a while I did get an error message this time. The problem indeed seems to be in OpenGL, more specifically in the shading library. Apparently we have GLSL 1.50 installed here, which is not supported. I'll try to find out if there's anything I can do about that (we're on a Scientific Linux 7 cluster, and I'm clearly not the only person using it...)

**Comment by mancellin** [comment]
Hi @sitadrost 
Did you manage to fix your display problem?

**Comment by sitadrost** [comment]
Hi @mancellin,
No, the problem seems to be in the OpenGL on our cluster, and I can't really do anything about that unfortunately.

**Comment by mancellin** [comment]
Ok. If you don't mind, I'll close the issue. Feel free to reopen it if there is anything that could be done in Capytaine to solve your problem.
