### ISSUE TITLE
Problem with qt dependency on Windows

### ISSUE THREAD

**Issue by mancellin** [mancellin/capytaine#19]
I have tried to install capytaine on windows x64, using the Anaconda prompt (Miniconda3).
The command: `conda install -c conda-forge capytaine`
gave me this error message:

```
ERROR conda.core.link:_execute(700): An error occurred while installing package
'conda-forge::qt-5.9.7-h506e8af_3'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::qt-5.9.7-h506e8af_3
location of failed script: C:\Users\bguillouzouic\AppData\Local\Continuum\minico
nda3\Scripts.qt-post-link.bat
==> script messages <==

==> script output <==
stdout: 1 fichier(s) copi?(s).

stderr: 'chcp' n'est pas reconnu en tant que commande interne
ou externe, un programme ex?cutable ou un fichier de commandes.
'chcp' n'est pas reconnu en tant que commande interne
ou externe, un programme ex?cutable ou un fichier de commandes.
'chcp' n'est pas reconnu en tant que commande interne
ou externe, un programme ex?cutable ou un fichier de commandes.
```

Would you have an idea of what could be the issue ?

Thanks!

_Originally posted by @bzouic in https://github.com/mancellin/capytaine/issues/18#issuecomment-533639053_

**Comment by mancellin** [comment]
The problem comes from the `qt` package which is a dependency of `matplotlib` which is required by `capytaine`.

I suggest you look for help on Anaconda support (for instance, the same error message is mentioned there: https://github.com/ContinuumIO/anaconda-issues/issues/11269)

There is not much else I can do on my side. `matplotlib` is not really necessary for the core functions of `capytaine` and I might consider removing it from the dependencies in the future if it is causing troubles.

**Comment by zzhao-booth** [comment]
same message
```
ERROR conda.core.link:_execute(700): An error occurred while installing package
'conda-forge::qt-5.9.7-h506e8af_3'.
```

I cannot install anaconda even after complete uninstallation because of this, I tried to use miniconda and install qt, same message.

**Comment by mancellin** [comment]
Thank you @zzhao-booth for the feedback. For the record, are you also using Windows?

Anyway, I'll make the dependency optional in the next release of Capytaine.

**Comment by zzhao-booth** [comment]
Yes, it's windows, I find it's because of something about the anaconda installer, I followed a suggestion on a Stackoverflow post and used anaconda 2019.03 installer and encountered no problem, I can install anaconda and Capytaine with no issue.

**Comment by bzouic** [comment]
Hello @zzhao-booth, thank you for your post. After the qt package issue I moved to ubuntu to use Capytaine. However, I am sure some users (and I) would be interested in using it on Windows. 
Could you share the link of the Stackoverflow post you followed and/or describe briefly the steps you followed to make it work on Windows? 
Thank you !

**Comment by mancellin** [comment]
I'm now releasing version 1.2.
Matplotlib is not mandatory any more to install Capytaine.

I'm closing the issue. Feel free to reopen it if you still have troubles.
