### ISSUE TITLE
Kochin function definition

### ISSUE THREAD

**Issue by dHofmeister** [mancellin/capytaine#22]
Dear mancellin, 

first of all, thank you and the developers of Nemoh for this awesome piece of work. 

I have a question regarding the kochin function. I've ran the calculations and wanted to convert it to drift forces (and also intend to compute Yaw Moment) however i'm a bit confused as to what specific kochin function this is? 

The "full" kochin function which has diffraction and radiation terms combined are only dependent on wave_freq and incidence_angle, however your kochin function seems to also be dependent on the 6-DOF components. This makes it seem like it's the radiation component of the kochin function only. Is this the case? Where is the diffraction component?

I've consulted some sources but they all point to Nemoh, and Nemoh itself outputs the kochin functions for diff and rad separately. Am I missing something? Do I need to compute them separately? 

Greetings and thanks again for your work and efforts

**Comment by mancellin** [comment]
Thank you for the kind words.

You're right, the Kochin function of the diffraction is not returned when using `fill_dataset` on a test matrix as in [the example in the cookbook](https://ancell.in/capytaine/latest/user_manual/cookbook.html#kochin-function).
That's an oversight on my part.
But it should be possible to compute it for each `result` object using [`compute_kochin`](https://ancell.in/capytaine/latest/developer_manual/api/capytaine.post_pro.kochin.html).

About the "full" Kochin function you are referring to: is it the Kochin function corresponding to the diffraction + the radiation due to the RAO motion? 
In this case, you'll need to compute the RAO and then sum the contributions of each dof to get the function you're looking for.

**Comment by dHofmeister** [comment]
Ah yes, I've figured it out using the `compute_kochin` function.  Thank you.

**Comment by mancellin** [comment]
Great! If you write a script to compute the drift force, it could be nice to include it in the cookbook for future users.

Anyway, I'll leave the issue open as a reminder for me to fix the missing diffraction Kochin function.

**Comment by dHofmeister** [comment]
Dear Mancellin, 

I've been trying to reproduce the findings of drift forces using your Capytaine software and I've so far have not been able to reproduce the same drift forces. 

My sources are these two documents: 
[1) Validation of Mean Drift Forces Computed
with the BEM Code NEMOH](https://vbn.aau.dk/ws/files/259654908/Drift_investigation.pdf)
[2) NEMOH's Matlab Toolbox/Routine](https://box.lheea.ec-nantes.fr/index.php/s/kYb6LwDly10o77N)

I've tried to reproduce the results of the floating sphere experiment in 1), with radius=1 and CG =[0,0,0].

But my results differ. The paper:
![image](https://user-images.githubusercontent.com/12850890/69970681-ef869c00-151e-11ea-87fc-0d05a1d6a160.png)
Mine (for Fx, with wave_direction=0 rad):
![image](https://user-images.githubusercontent.com/12850890/69971081-a8e57180-151f-11ea-924d-0ce33a0a1fa5.png)

The sign flip is wrong, the max value is wrong and the convergence to zero is wrong... basically everything. 

I believe that I am either fundamentally misunderstanding the kochin function and it's role in this drift force calculation or i've made a typo somewhere. 

I tried to follow the steps given in the sources, starting with computing the individual Kochin functions for radiation and damping. From this [1]:
![image](https://user-images.githubusercontent.com/12850890/69972116-52793280-1521-11ea-8195-89fd2040ec04.png)

I computed for radiation:


    for result in res_rad: # res_rad is a list of results of radiation problems
        # find the omega and dof idx used in a result
        omega_idx = [i for i, omega in enumerate(omegas) if result.omega == omega][0]
        dof_idx = [i for i, dof in enumerate(body.dofs) if result.radiating_dof == dof][0]
        # Store the complex valued kochin in the last dimension of the array for each theta in the thetas array.
        # omegas =linspace[0.1 to 2.1pi]
        # dofs =linspace[1 to 6]
        # thetas =linspace[-0.5pi to 0.5pi]
        kochin_radiation_array[omega_idx, dof_idx, :] = cpt.post_pro.compute_kochin(result, thetas)
This radiation component seems straight forward. For every wave frequency and degree of freedom, compute the Kochin function for the given angles of 'thetas'. 
        

For the Diffraction component I've written:

    for result in res_dif:  
	    # find the omega and wave direction idx used in a result  
	    omega_idx = [i for i, omega in enumerate(omegas) if result.omega == omega][0]  
	    wave_direction_idx = [i for i, wave_direction in enumerate(wave_directions)  
                              if result.wave_direction == wave_direction][0]  
        # Store the complex valued kochin in the last dimension of the array for each theta in the thetas array.  
        kochin_diffraction_array[omega_idx, wave_direction_idx, :] = cpt.post_pro.compute_kochin(result, thetas)

>Since the radiation result is dependent on omega and wave_dir, the third dimension is now populated by kochin's thetas. (Is my thinking wrong here?)

I'm getting confused as to the true physical meaning of this Kochin function now. Given a frequency and incidence angle, compute the Kochin function for the given thetas. I dont see the distinction between wave incidence angle and kochin angles theta. Are they the same physical property? Does the Kochin angle theta operate as superposition on the wave incidence angle? For example: incidence angle of -1 rad, but computed kochin theta of +1 rad,  Does this compute the Kochin function for angle = 0 rad in the global reference frame? I feel like im making a mistake here. 

from this point forward, I use equation [1] for the diffraction related part as (this is an array multiplication of size[omegas, wave_dir, thetas]:

    wave_amplitude = 1   
    # Diffraction component of the complex kochin function  
    complex_kochin_diffraction = wave_amplitude * data.kochin_diffraction * np.exp(np.complex(0, 1) * (np.pi / 2))
and for the radiation part:

    for omega_idx in range(len(data.omega)):  
	    for wave_direction_idx in range(len(data.wave_direction)):  
	        scalar = np.exp(np.complex(0, -1) * (np.pi / 2)) * np.complex(0, 1) * data.omega[omega_idx]  
	        array = (np.matmul(data.kochin_radiation[omega_idx, :, :].values, data.RAO[wave_direction_idx, omega_idx, :].values))  
	        complex_kochin_radiation[omega_idx, wave_direction_idx, :] = np.multiply([scalar], array)


leading to:

    data['complex_kochin'] = np.add(complex_kochin_diffraction, complex_kochin_radiation)

now implementing:
![image](https://user-images.githubusercontent.com/12850890/69975874-4fce0b80-1528-11ea-8690-8a566284fa8a.png)

as:

    wave_amplitude = 1 
    for wave_direction_idx in range(len(data.wave_direction)):  
	    for omega_idx in range(len(data.omega)):
	        wavelength = 1 / data.coords['wavenumber'][omega_idx]  # wavelength = 1 / wavenumber
	        wavelength_deep_water = 1 / (np.power(data.omega[omega_idx], 2) / data.g)  # wavelength = 1 / wavenumber  
	         # Pre-calculate leading parameters 
	         # -2pi * A * w  
	         constant_1 = -2 * np.pi * wave_amplitude * data.omega[omega_idx] 
	         # -8pi * rho * k(k0*h)^2 / (h * [ k*h - (k0*h)^2 + k0*h])  
	         constant_2 = -8 * np.pi * data.coords['rho'] * wavelength * \
	         np.power(wavelength_deep_water * water_depth, 2)\  
            / (water_depth * (np.power(wavelength * water_depth, 2)  
                              - (np.power(wavelength_deep_water * water_depth, 2)  
                                 + wavelength_deep_water * water_depth)  
                              )  
               )  
  
        "The drift forces are a combination of radiation and diffraction kochin functions"  
        #  constant_1 *  
        #  cos(beta) * Im(complex_kochin(beta,w) + 
        #  constant_2 * 
        # trapezoid(Real(complex_kochin(theta, w))*Imag(Conj(complex_kochin(theta,w))) * cos(theta) :: d_theta)  
        
        drift_force_x[wave_direction_idx, omega_idx] = 
	        constant_1 * np.cos(data.wave_direction[wave_direction_idx]) * \  
            np.imag(data['complex_kochin'][omega_idx, wave_direction_idx, wave_direction_idx]) \  <--- This line is probably wrong (?), use wave_direction_idx twice 
            + \  
            constant_2 * np.trapz(np.real(data['complex_kochin'][omega_idx, wave_direction_idx, :]) *  
                                  np.imag(np.conj(data['complex_kochin'][omega_idx, wave_direction_idx, :])) *  
                                  np.cos(data.theta), x=data.theta)

> I think i made a mistake in "np.imag(data['complex_kochin'][omega_idx, wave_direction_idx, wave_direction_idx])" the third index is actually the theta axis. 

but if i both use a wave_direction_range and also theta from -0.5pi to 0.5pi with the same number of elements, then i can do this right? "Given wave direction x, take the kochin value assosiated with x", this wil, with the same ranges and elements, be the same index for theta and wave_direction? Or am i conceptually wrong here?

> also: The literature and the NEMOH matlab routine seems to mix up wavenumber and wavelength. The documents i've mentioned before specifically mention wavelength but the matlab code says wavenumber and also calculates the wavenumber, not the wavelength.  

Either way I dont know where i'm wrong. 

One side note: I don't know where to place the ref_point for the far-field calculation. Ideally this would be at some value p with lim p-> inf right? But a large value leads to a very different plot:

ref_point=(10000000,0), with the sphere's center at (0,0,0):
![image](https://user-images.githubusercontent.com/12850890/69976888-0c749c80-152a-11ea-99ca-386d6019eeb7.png)


My full code can be found [here](https://github.com/dHofmeister/Maritime-Dynamical-Modeling). 

It is the first part of the goal to build a simulator in matlab straight from a 3D mesh. 

I hope I can give some form of contribution. I don't ask of you to do a full scan of my code, that's simply too much of a hassle. I'm just posting this in the hopes that maybe you could spot some obvious mistake somewhere. I will continue my research into this and hopefully I will be able to fix this and be able to reproduce their results.

Greetings
Deniz

**Comment by mancellin** [comment]
After a very shallow read of your code, it looks okay.
You might make the code slightly more readable (and then spot a typo) by replacing `np.power(x, 2)` by `x**2`, `np.matmul` by `@` and `np.complex(0, 1)` by `1j`.

> Since the radiation result is dependent on omega and wave_dir, the third
> dimension is now populated by kochin's thetas. (Is my thinking wrong here?)

That sounds correct.

> I'm getting confused as to the true physical meaning of this Kochin function
> now. Given a frequency and incidence angle, compute the Kochin function for
> the given thetas. I dont see the distinction between wave incidence angle and
> kochin angles theta. Are they the same physical property? Does the Kochin
> angle theta operate as superposition on the wave incidence angle? For example:
> incidence angle of -1 rad, but computed kochin theta of +1 rad, Does this
> compute the Kochin function for angle = 0 rad in the global reference frame? I
> feel like im making a mistake here.

In general, the incoming wave angle β and the direction θ of evaluation of the far-field coefficient are independant. Both angles are defined in the same cylindrical coordinates in the global frame.

However, because your mesh is an axi-symmetrical sphere, your problem is invariant upon rotation: the far field in direction θ=1 for waves coming from β=0 is the same as the far field in direction θ=0 for waves coming from β=-1. For this particular body, only one diffraction problem is actually necessary.

> I think i made a mistake in "np.imag(data['complex_kochin'][omega_idx,
> wave_direction_idx, wave_direction_idx])" the third index is actually the
> theta axis.
> but if i both use a wave_direction_range and also theta from -0.5pi to 0.5pi
> with the same number of elements, then i can do this right? "Given wave
> direction x, take the kochin value assosiated with x", this wil, with the same
> ranges and elements, be the same index for theta and wave_direction? Or am i
> conceptually wrong here?

Yes, that sounds right.
(This is one of the advantage of `xarray.DataArray` over bare `numpy` arrays: you can ask for the value at a given coordinate without worrying about the index of this coordinate in the range of coordinates.)

> One side note: I don't know where to place the ref_point for the far-field
> calculation. Ideally this would be at some value p with lim p-> inf right?

No, it is the center of the cylindrical coordinates in which the Kochin function is computed.
The center of the sphere should be fine.

**Comment by dHofmeister** [comment]
Dear mancellin, 
thank you for your time. I will make the code more readable as you suggested. 

Based on your comments it seems that you think my thought process is correct and there simply is some error in the details. I will look into it. Thank you. Hopefully i'll be able to reproduce the paper soon.

**Comment by mancellin** [comment]
@dHofmeister Did you manage to solve your issue with the drift force?

About the original problem of this thread: the missing `kochin_diffraction` is now computed in version 1.2.
For backward compatibility, `kochin` still denotes the Kochin function of the radiated waves.

I'm closing the issue. Feel free to reopen it if you have any troubles.

**Comment by bzouic** [comment]
Hello @dHofmeister and @mancellin, 

First, I would like to thank you for your work. 

I am a new user of Capytaine. I made comparisons of first order loads and motion RAO with OrcaWave results for a vertical cylinder and I got the exact same results.
Capytaine would be very interesting for my work if I could calculate the second order mean drift load. 

Would you have a python piece of script for this calculation ? Did you validated this calculation with respect to another code ?

Thank you very much,

**Comment by mancellin** [comment]
@bzouic Thank you for your interest. On my side, there has been nothing new on this topic since the last message.
