### ISSUE TITLE
[noissue] Merry Christmas

### ISSUE THREAD

**Issue by RubendeBruin** [mancellin/capytaine#24]
Apologies for using the issues functionality for this, do not know where else to place it. 

I used capytaine to produce the hydrodynamics for the vessel in this video, and I thought it was nice to pay tribute by sharing the result (click image to play video).

[![Merry Christmas](http://img.youtube.com/vi/UgR0I9g6tww/0.jpg)](http://www.youtube.com/watch?v=UgR0I9g6tww "Merry Christmas")

Merry Christmas and thanks for the great tool!

**Comment by mancellin** [comment]
Thank you. It is a nice present to know that my work is used and appreciated :)

Merry Christmas to you too!
