### ISSUE TITLE
Help compiling for development on OSX

### ISSUE THREAD

**Issue by ryancoe** [mancellin/capytaine#31]
I noticed in #11 you had some discussion about compiling on OSX. I was happily using the `Conda-forge` distribution, but now I'm interested in contributing and thus want to compile `capytaine` locally.

I had some trouble compiling locally using the `Makefile` and `setup.py` as directed in the [documentation](https://ancell.in/capytaine/latest/developer_manual/installation.html), until I set the following to make `distutils` call my `homebrew` installed compilers instead the ones from `Xcode` (not sure if all of these are necessary).

```bash
export CC=/usr/local/bin/gcc-9
export CXX=/usr/local/bin/g++
export CPP=/usr/local/bin/cpp
export LD=/usr/local/bin/gcc-9
alias c++=/usr/local/bin/c++
alias g++=/usr/local/bin/g++
alias gcc=/usr/local/bin/gcc-9
alias cpp=/usr/local/bin/cpp
alias ld=/usr/local/bin/gcc-9
alias cc=/usr/local/bin/gcc-9
```

After running compiling successfully, I went to test the installation with `python -m pytest` and realized I needed the additional following packages: `quadpy`, `hypothesis`, `matplotlib`, `vtk` (couldn't get this to work, probably similar to #28).

Anyhow, I was about to ask for help, but figured it out and thought maybe someone else might find this useful.

EDIT: actually the `vtk` functionality works fine. The error in `test_ui_vtk.py` was caused by the line `animation.embed_in_notebook()`- so you must have `ipython` as well.

https://github.com/mancellin/capytaine/blob/4fb70c71bd791272cca548a4ea0c92b24a49622f/pytest/test_ui_vtk.py#L13

**Comment by mancellin** [comment]
Thank you for your feedback. The documentation is indeed missing a list of the packages required for testing.

**Comment by ryancoe** [comment]
mostly this my own naiveté... just thought some else might find this useful in the future

**Comment by ryancoe** [comment]
Note that if you've recently moved from Mojave to Catalina, you may need to call

```bash
brew reinstall gcc
brew reinstall gfortran
```
