### ISSUE TITLE
Problems to use it after installation

### ISSUE THREAD

**Issue by Matosinho** [mancellin/capytaine#34]
Hi! Firstly, I'm very excited to use the package, it seems to be really great. I don't know if there was a problem with installation, but no error appeared on screen. After I did everything, when I execute from capytaine import *, the following error appears:

![image](https://user-images.githubusercontent.com/40249250/83596999-7ce19200-a53c-11ea-9a39-af760cdb9038.png)

**Comment by mancellin** [comment]
It looks like a Python version problem.
Which version of Python are you using (3.6 or higher is required)? and how did you install Capytaine?

**Comment by Matosinho** [comment]
Sorry for the trouble, it is my first time using only python, normally I just use it with ROS. I installed an IDE and it worked. Firtly I was trying only with terminal. Thank you!
