### ISSUE TITLE
capytaine installation: error with versioning

### ISSUE THREAD

**Issue by ffrancesco** [mancellin/capytaine#39]
hi @mancellin, I've tried to install capytaine using conda, but it seems like the installed version is 1.0.1 and not 1.2, as you can see in the output of pip freeze command.

I m working on OSX 10.15.4, but I had the same problem with 10.14.X.

```bash
pip freeze

attrs==19.3.0
capytaine==1.0.1
certifi==2019.11.28
cftime==1.2.0
cycler==0.10.0
future==0.18.2
gmsh==4.6.0
h5py==2.10.0
helpers==0.2.0
importlib-metadata==1.7.0
kiwisolver==1.1.0
matplotlib==3.2.1
meshio==4.0.16
netCDF4==1.5.3
numpy==1.19.0
pandas==1.0.3
pygmsh==6.1.1
pyparsing==2.4.6
python-dateutil==2.8.1
pytz==2019.3
scipy==1.3.1
six==1.15.0
tornado==6.0.4
vedo==2020.3.4
vtk==9.0.1
xarray==0.15.0
zipp==3.1.0
```

**Comment by mancellin** [comment]
What happens when you force the version to install ?
```
conda install -c conda-forge capytaine=1.2
```

If it fails, could you try to update all conda packages?
```
conda update --all
```

**Comment by mancellin** [comment]
See also the similar issue #26

**Comment by ffrancesco** [comment]
@mancellin explicitly pointing at the version during the installation works, 
but it creates an error when assembling the dataset if not followed by 
```
conda update -all
```
thanks

**Comment by ryancoe** [comment]
I wound up making a conda enviroment specifically for capytaine when I ran into this problem a while back.
