### ISSUE TITLE
TLP computation help: mass/CoG of the structure, external force, mooring, etc

### ISSUE THREAD

**Issue by yonghoonlee** [mancellin/capytaine#42]
I am new to hydrodynamics, and I am implementing Tension-leg platform with the Capytaine.
I have a sample WAMIT input for the TLP system and trying to interpret that WAMIT input file into the Capytaine input script. However, I do not find many of features that I need from the Capytaine tutorial.

The purpose is to obtain (1) added mass matrix at infinite frequency, (2) damping and hydrostatic matrices, (3) Froude-Krylov forces and phases, and (4) diffraction forces and phases.

First, how do I specify mass and center of gravity to the input? I was looking for 
The hydrodynamic system only has immersed geometry, but the overall mass is located far above sea level, and need to put a mass matrix (including moment of inertia value as well).

Second, how do I specify external forces or stiffness, such as mooring line tension, etc?

Do you have more applied examples beyond those included in the current docs?
Thank you.

**Comment by mancellin** [comment]
Hi,

- Inertia and hydrostatic stiffness are unfortunately not computed by Capytaine. See also #36.
- The core feature of Capytaine is the hydrodynamics (added mass, radiation damping, diffraction forces). The only role of the centre of mass would be for the definition of the rotation degrees of freedom. Look for the documentation of `cpt.FloatingBody.add_rotation_dof` and `cpt.Axis` for detail on how to define the rotation dofs.
- Once you have all hydrostatic and hydrodynamic forces, you'll want to solve the equation of motion of the body. Capytaine includes a very basic frequency domain solver in `cpt.post_pro.rao`. But for a tension-leg platform, you will probably need a time domain solver in which you can include non-linear forces such as mooring. This is out of the scope of Capytaine.

**Comment by RubendeBruin** [comment]
Hi  yonghoonlee,

what kind of TLP are you trying to model and in what kind of configuration? (wet tow, half installed, installed). Especially TLPs with columns (like https://nl.wikipedia.org/wiki/Mars_(olieveld)#/media/Bestand:Mars_Tension-leg_Platform.jpg) can be difficult if the top of the pontoons are close to the waterline.

In my experience post installation behavior (tendons tensioned) can be modeled quite accurately in frequency domain.

I'm not sure that you need the mass and center of gravity for the calculation. In WAMIT you can supply them but to my knowlegde it is only used for calculation of the motion RAOs and second order (wave-drift) forces.

**Comment by yonghoonlee** [comment]
Hi @mancellin 

Thank you for your response. I will look into the #36 and see if I can implement external tool for calculating inertia and hydrostatic stiffness information.

Hi @RubendeBruin 

I am modeling small-sized four-column (center-column + three outer-column distributed in 120 degree to each other) TLP. The pontoon is located in the very bottom of the TLP, so it will be at least submerged over 10 meters below the water surface. Thus, it may not be very difficult to be modeled or simulated, since there will be no chance that pontoon can be exposed over the water surface. Eventually, I need to evaluate all the situations, including towing and post-installed operating conditions, but my main concern is the post-installation part. 

Thank you for clarifying infos. As @mancellin mentioned, I think the mass matrix is utilized for determining the axis of rotation for the rotating degrees of freedom. Then, that can be externally calculated without involvement of hydrodynamics.

Thank you all for the clarifications.

**Comment by yonghoonlee** [comment]
@mancellin I am looking for ways to obtain infinite frequency results.
In WAMIT, if omega value is set to -1, then the code gives infinite frequency quantities, such as added mass.
In Capytaine, how do I get the infinite frequency added mass?
I tried with a fairly large frequency value, but Capytaine required finer mesh for that, so I could not get the result.
Is it possible in different way, such as omega=-1 in WAMIT?
Thank you.
