### ISSUE TITLE
Infinite frequency quantities (e.g. added mass) calculation

### ISSUE THREAD

**Issue by yonghoonlee** [mancellin/capytaine#43]
I am looking for ways to obtain infinite frequency results.
In WAMIT, if omega value is set to -1, then the code gives infinite frequency result quantities, such as added mass.
In Capytaine, how do I get the infinite frequency added mass?
Instead of stating infinite frequency directly, I just tried with a fairly large frequency value as a proxy of infinite frequency, but Capytaine required finer mesh for that, so I could not get the result. Is it possible in different way, such as omega=-1 in WAMIT? Thank you.

**Comment by mancellin** [comment]
Capytaine uses the standard floating point number representation to encode infinite values. To pass it as parameter in a Python script, you can use `float('inf')` or `numpy.infty`.

However, note that the infinite frequency case `omega=np.infty` has not been implemented for all combinations of parameters (infinite water depth should work but not finite water depth).

**Comment by yonghoonlee** [comment]
I set infinite water depth and tested with the infinite frequency.
However, I got following messages:

```
The rotation dof Roll has been initialized around the origin of the domain (0, 0, 0).
The rotation dof Pitch has been initialized around the origin of the domain (0, 0, 0).
The rotation dof Yaw has been initialized around the origin of the domain (0, 0, 0).
/Users/yonghoonlee/opt/anaconda3/envs/capytaine/lib/python3.8/site-packages/capytaine/bem/airy_waves.py:82: RuntimeWarning: invalid value encountered in multiply
  np.exp(1j * k * wbar) * \
Resolution of the mesh (8×max_radius=1.01e+01) might be insufficient for this wavelength (wavelength=0.00e+00)!
Resolution of the mesh (8×max_radius=1.01e+01) might be insufficient for this wavelength (wavelength=0.00e+00)!
Resolution of the mesh (8×max_radius=1.01e+01) might be insufficient for this wavelength (wavelength=0.00e+00)!
Resolution of the mesh (8×max_radius=1.01e+01) might be insufficient for this wavelength (wavelength=0.00e+00)!
Resolution of the mesh (8×max_radius=1.01e+01) might be insufficient for this wavelength (wavelength=0.00e+00)!
Resolution of the mesh (8×max_radius=1.01e+01) might be insufficient for this wavelength (wavelength=0.00e+00)!
Resolution of the mesh (8×max_radius=1.01e+01) might be insufficient for this wavelength (wavelength=0.00e+00)!
No convergence of the GMRES. Error code: 36480
Resolution of the mesh (8×max_radius=1.01e+01) might be insufficient for this wavelength (wavelength=0.00e+00)!
No convergence of the GMRES. Error code: 36480
Resolution of the mesh (8×max_radius=1.01e+01) might be insufficient for this wavelength (wavelength=0.00e+00)!
No convergence of the GMRES. Error code: 36480
Resolution of the mesh (8×max_radius=1.01e+01) might be insufficient for this wavelength (wavelength=0.00e+00)!
No convergence of the GMRES. Error code: 36480
Resolution of the mesh (8×max_radius=1.01e+01) might be insufficient for this wavelength (wavelength=0.00e+00)!
No convergence of the GMRES. Error code: 36480
/Users/yonghoonlee/opt/anaconda3/envs/capytaine/lib/python3.8/site-packages/capytaine/bem/airy_waves.py:45: RuntimeWarning: invalid value encountered in multiply
  return -1j*pb.g/pb.omega * cih * np.exp(1j * k * wbar)
```

I saw similar error (but without RuntimeWarnings) for the high frequency values, such as omega>3.0 for this geometry.
This geometry is one that I obtained from an offshore engineering company who uses WAMIT for their engineering work, and worked fine with WAMIT for calculating infinite frequency cases as well as omega values up to 6.0. However, it seems that capytaine requires finer mesh for obtaining results for higher frequency values. I am not sure the resolution itself is relevant to the error I see for the infinite frequency case, though.

Thank you for your help, and I appreciate the code you developed. I have no access to WAMIT, so I need to replicate the result came out from WAMIT with open source tools, and capytaine seems the best tool among several I have explored.

**Comment by dav-og** [comment]
@mancellin the Green functions can compute added mass at infinite frequency (AM(inf)) this way in Capytaine?

in Nemoh, AM(inf) would be computed by postProcessor/IRF.f90
you can see the code relating to that (and IRF calculation) here:
https://github.com/LHEEA/Nemoh/blob/49393be96bd590e267bfbc16347b665cda0edeb8/postProcessor/IRF.f90#L116

there is an explanation of these equations in Folley (2016) - Numerical Modelling of Wave Energy Converters - Eq 3.27:
https://www.sciencedirect.com/science/article/pii/B9780128032107000037#s0045

**Comment by mancellin** [comment]
@dav-og 
The infinite depth Green function has a very simple expression for ω=0 and ω=∞ (see e.g. eq. (5) of Xie et al. Applied Ocean Research 2018). It is implemented in Capytaine, although it has not really been thoroughly tested.

I had forgotten about the other expression you mentioned. They are not implemented in Capytaine, but they are in the scope of the code and I would accept a pull request with them. A comparison with the direct BEM resolution for ω=∞ would be interesting.

@yonghoonlee 
The warning regarding the resolution of the mesh is probably not relevant for ω=∞. Do you get a results that looks reasonable?

Indeed, WAMIT might use a higher resolution method and thus require less panels for the same precision.
