### ISSUE TITLE
Clipping of mesh results in zero face areas

### ISSUE THREAD

**Issue by RubendeBruin** [mancellin/capytaine#46]
I'm trying run a comparison between OrcaWave and capytaine. I have received a wamit geometry file (attached as .txt).
It looks fine, but as soon as I clip it I get zero triangle areas.

![image](https://user-images.githubusercontent.com/34062862/96629772-5fa73780-1314-11eb-9942-b32d62a27049.png)

Note that I translate the mesh by 0.01 before clipping to work around a "Exception: Face 3 clipping case 031 not known." error in the clipper. But also if I translate by other values I keep getting zero areas.

Clipping of mesh

```python
    boat = cpt.FloatingBody.from_file(r"FPOS Mesh-ORCAWAVE.txt", file_format="gdf", name="FPSO")

    areas = boat.mesh.faces_areas
    print(f'min..max = {min(areas)} .. {max(areas)}')

    boat.translate_z(0.01)

    areas = boat.mesh.faces_areas
    print(f'min..max = {min(areas)} .. {max(areas)}')

    boat.clip(Plane(normal=(0, 0, 1), point=(0, 0, 0)))

    areas = boat.mesh.faces_areas
    print(f'min..max = {min(areas)} .. {max(areas)}')
```

[FPOS Mesh-ORCAWAVE.txt](https://github.com/mancellin/capytaine/files/5410765/FPOS.Mesh-ORCAWAVE.txt)

**Comment by RubendeBruin** [comment]
adding ```boat.mesh.heal_mesh()``` after importing solves the issue. But not sure if the mesh file was wrong (did not make it myself, was used for analysis in other programs) or that there is something going wrong during the loading.

**Comment by mancellin** [comment]
I'm not sure what is happening here. Maybe it would be safer to add a call to `heal_mesh` in `FloatingBody.from_file`.
