### ISSUE TITLE
Turning off multi-thread computation

### ISSUE THREAD

**Issue by yonghoonlee** [mancellin/capytaine#47]
I would like to turn off the multiprocessing, so I tried:
```
os.environ['OMP_NUM_THREADS'] = 1
os.environ['MKL_NUM_THREADS'] = 1
```
However, it is not working. All the CPU cores are utilized.

When I put the environmental variable outside of the code (e.g., in .bashrc file) it works.
However, I do not have control for those files for other computers.
I hope to implement this in my python code.

Are there a Capytaine API for controlling the number of threads?

**Comment by mancellin** [comment]
Yes, IIRC I had some issues trying to change these settings from within Python.

On Linux, you can set environment variable when calling a program from the terminal as
```
OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 python my_script.py
```

Note that there is nothing specific to Capytaine here and you can search on the internet for better solutions to control OpenMP.

**Comment by mancellin** [comment]
A late update in case somebody stumbles upon this thread: you can control the number of threads from within Python using the [threadpoolctl library](https://github.com/joblib/threadpoolctl)
```python
from threadpoolctl import ThreadpoolController
controller = ThreadpoolController()
with controller.limit(limits=1, user_api='blas'):
    with controller.limit(limits=1, user_api='openmp'):
        cpt.BEMSolver().solve(...)
```
I'm considering integrating this library to future versions of Capytaine with better parallelism.
