### ISSUE TITLE
Question on diffraction force computation

### ISSUE THREAD

**Issue by yonghoonlee** [mancellin/capytaine#49]
I am computing TLP using the capytaine and comparing to WAMIT results.
I was looking for theory manuals of both codes to understand diffraction forces, but I could not find the equations in detail.

In WAMIT, there are three relevant output files:
- *.3 file: Exciting Force
- *.3fk file: Froude-Krylov Component
- *.3sc file: Scattering Component
and they have following columns (that has omega, wave_heading, amplitude, phase, real, imaginary columns).

In capytaine, there are two output data:
- diffraction_force
- Froude_Krylov_force

It seems that Froude_Krylov_force corresponds to *.3fk file.
Here, how do I calculate rest of the results and compare with WAMIT results?
Is *.3 file (Exciting Force) corresponds to "diffraction_force" in capytaine?
If that is true, could you let me know how I can calculate Scattering Components out of these two output?

Thank you.

**Comment by mancellin** [comment]
I'm not familiar with WAMIT's file format, but I would guess that:
- WAMIT's "scattering component" corresponds to Capytaine's "diffraction force";
- WAMIT's "exciting force" is the sum of the other two. When computed by Capytaine, it would be called "excitation force".

**Comment by yonghoonlee** [comment]
Thank you. That helps a lot. I also tried to match data between two solvers, and it seems your guess is correct.
