### ISSUE TITLE
Tips for Creating polygons

### ISSUE THREAD

**Issue by sharmi0** [mancellin/capytaine#52]
Hi, I'm a little bit of a beginner but I had a couple questions:

Is there a way to create a polygon prism in capytaine or does it have to be imported as a mesh from a different software?
I know quadpy has been a recent added feature, but the capytaine website mentions that only quadrilaterals are possible at the moment so I was not too sure about using that feature. 

Additionally, I would like to model an object that has some thrust so it is moving with a velocity in some directions. Do you have any advice on how I could model this using the capytaine functions. Thanks!

Finally, is a mesh from Abaqus or Solidworks compatible with Capytaine?

**Comment by mancellin** [comment]
Hi, thank you for your interest in Capytaine.

No, this kind of geometry cannot be automatically generated by Capytaine and you should rely on a dedicated meshing software.
There is indeed an experimental integration of Quadpy but this is not for the generation of new meshes, but for the numerical integration of function on meshes.

No, Capytaine is assuming that objects are doing small oscillations around a static position. There are linear potential flow models of objects moving with a constant velocity, but they are not implemented in Capytaine and I am not very familiar enough with them to tell you how hard it would be to include them.

The list of mesh formats that can be imported by Capytaine is available in the documentation. If Abaqus or Solidwork cannot export your mesh to one of them, you will need to find a way to do the conversion. Maybe with Gmsh or Paraview or something like that.

**Comment by sharmi0** [comment]
Thank you so much for your response!
