### ISSUE TITLE
keep_only_dofs uses 'inertia_matrix' (not 'mass')

### ISSUE THREAD

**Issue by ryancoe** [mancellin/capytaine#56]
The [`keep_only_dofs`](https://github.com/mancellin/capytaine/blob/4fb70c71bd791272cca548a4ea0c92b24a49622f/capytaine/bodies/bodies.py#L169-L179) method removes extra coordinates from the inertia and hydrostatic stiffness data variables, but the naming for the inertia variable is inconsistent with [`hydrostatics_dataset`](https://github.com/mancellin/capytaine/blob/4fb70c71bd791272cca548a4ea0c92b24a49622f/capytaine/io/xarray.py#L161-L172).

- [`keep_only_dofs`](https://github.com/mancellin/capytaine/blob/4fb70c71bd791272cca548a4ea0c92b24a49622f/capytaine/bodies/bodies.py#L174-L175): uses `inertia_matrix`
- [`hydrostatics_dataset`](https://github.com/mancellin/capytaine/blob/4fb70c71bd791272cca548a4ea0c92b24a49622f/capytaine/io/xarray.py#L161-L172): uses `mass`

https://github.com/mancellin/capytaine/blob/4fb70c71bd791272cca548a4ea0c92b24a49622f/capytaine/bodies/bodies.py#L169-L179

https://github.com/mancellin/capytaine/blob/4fb70c71bd791272cca548a4ea0c92b24a49622f/capytaine/io/xarray.py#L161-L172

**Comment by mancellin** [comment]
Good point. Everything related to hydrostatic in the code might be lacking some polish and testing.

Would you like to submit a pull request to fix that?

**Comment by ryancoe** [comment]
Looks like the `mass` name is also used in `rao`, so I suppose we can convert to that.

https://github.com/mancellin/capytaine/blob/4fb70c71bd791272cca548a4ea0c92b24a49622f/capytaine/post_pro/rao.py#L15-L66

**Comment by mancellin** [comment]
Yes, as well as in an example in the cookbook: https://github.com/mancellin/capytaine/blob/4fb70c71bd791272cca548a4ea0c92b24a49622f/docs/user_manual/examples/boat_animation.py#L23-L30

I feel like `inertia` or `inertia_matrix` might be a better name, because people could expect `body.mass` to be a scalar. But `mass` is already (almost) documented and it is not worth a breaking change.
