### ISSUE TITLE
quadpy changed API

### ISSUE THREAD

**Issue by ryancoe** [mancellin/capytaine#57]
It looks like [`quadpy`](https://github.com/nschloe/quadpy) underwent a major revision at [v0.15](https://github.com/nschloe/quadpy/releases/tag/v0.15.0), which has broken [`test_bem_with_quadratures.py `](https://github.com/mancellin/capytaine/blob/master/pytest/test_bem_with_quadratures.py).

I don't understand here what's going in this function enough, but I imagine the fix is not too challenging.

**Comment by mancellin** [comment]
Indeed, see #48

Since that feature is not the most useful, I'm waiting for quadpy's API to stabilize (with a 1.0 version or something) before I try to fix it.

**Comment by ryancoe** [comment]
not sure how I missed #48, sorry!

**Comment by mancellin** [comment]
No problem, thank you for reporting the issue.
