### ISSUE TITLE
Return impedance matrix?

### ISSUE THREAD

**Issue by ryancoe** [mancellin/capytaine#61]
It looks like the [`rao`](https://github.com/mancellin/capytaine/blob/bb794dd5fbc1eb5925226d8f7c5f3a734ba4d356/capytaine/post_pro/rao.py) function already calculates impedance. It might be helpful to return this also? Or write a separate function which [`rao`](https://github.com/mancellin/capytaine/blob/bb794dd5fbc1eb5925226d8f7c5f3a734ba4d356/capytaine/post_pro/rao.py) calls but can also be called independently (I guess this I prefer this approach)? I'm happy to implement this @mancellin if you agree and want to weigh in on the preferred approach.

https://github.com/mancellin/capytaine/blob/bb794dd5fbc1eb5925226d8f7c5f3a734ba4d356/capytaine/post_pro/rao.py#L44-L52

![image](https://user-images.githubusercontent.com/5589887/115271019-24869500-a0fa-11eb-94ef-8b326d530b0c.png)

**Comment by mancellin** [comment]
Sure, that makes sense to have a dedicated function for that.

**Comment by mancellin** [comment]
Might also be a good opportunity to mention `rao` and the new function in the docs.
https://github.com/mancellin/capytaine/blob/bb794dd5fbc1eb5925226d8f7c5f3a734ba4d356/docs/user_manual/post_pro.rst
