### ISSUE TITLE
Calculating RAO

### ISSUE THREAD

**Issue by sharmi0** [mancellin/capytaine#66]
I'm trying to calculate the RAO for a mesh. Is there a way to do this without inputting the added mass and hydrostatic coefficient matrices? 
In the cookbook example in the documentation the RAO is calculated by first inputting the two matrices, but I don't have the added mass/hydrostatic coefficients for my mesh. 
If the RAO solver needs the added mass and hydrostatic coefficient matrices can I calculate these matrices separately in capytaine and then plug in the matrices I find from capytaine into the RAO calculator?

Thanks!

**Comment by mancellin** [comment]
Yes, you will need them to compute the response of the body to the waves (the RAO).
See #55 and #64 for discussions on the computation of the hydrostatics.

**Comment by sharmi0** [comment]
Thank you! Is there a way to download meshmagick for python 3.8. I'm trying to install using conda and it gives me an error saying meshmagick needs 2.7.

**Comment by mancellin** [comment]
The conda package might be out of date. This will install the latest version:
```
pip install https://github.com/LHEEA/meshmagick/archive/master.zip
```

**Comment by sharmi0** [comment]
Thanks! My object is too small so the finest mesh I can get is still too large for the wavelengths I want to test. Do you know if I can break the mesh into smaller pieces and test each? How I would combine their solutions to get an accurate value for the whole mesh put together?

**Comment by mancellin** [comment]
I'm not sure to understand your question.
Is this about the warning "Resolution of the mesh might be insufficient for this wavelength"? This is about the size of the panels in the mesh, not the size of the body.

**Comment by sharmi0** [comment]
Yes what I'm asking is related to that warning. I'm unable to make the mesh finer at some point and run capytaine because it requires too much RAM. So I was thinking about breaking down the mesh into smaller sized chunks. 
Is it typical to need this kind of resolution? The only way this can be fixed is using a different wavelength, which would defeat the purpose, or using very small meshes. Is that correct? Or does using larger bodies help somehow?

![image](https://user-images.githubusercontent.com/80690027/116550047-3d463600-a8c4-11eb-9a9e-d14f4d9451f8.png)

**Comment by RubendeBruin** [comment]
Can you post a picture of the mesh? Or the mesh itself?

**Comment by ryancoe** [comment]
I think your body has a heave natural frequency on the order of 0.2 rad/s. So if you have the computing power and want to spend the time, you can refine the mesh and run calculations `omega_range = np.linspace(0.1, 6.0, 20)`, but these high frequencies are really just ripples that cannot effect your body.

```python
import pygmsh
import gmsh
import matplotlib.pyplot as plt
import numpy as np
import capytaine as cpt

import meshmagick.hydrostatics as hs
import meshmagick.mesh as mm

from scipy.linalg import block_diag

import logging
logging.basicConfig(level=logging.INFO, format='%(levelname)-8s: %(message)s')

#%%


def pol2cart(rho, phi):
    x = rho * np.cos(phi)
    y = rho * np.sin(phi)
    return(x, y)


offset = 0.01   # small offset so we can trim at the free surface
r = 2e3/2       # radius
T = 200         # draft
n = 6           # number of sides

ms = 0.1       # mesh scale factor (smaller -> more cells)
        

#%%

with pygmsh.occ.Geometry() as geom:
    gmsh.option.setNumber('Mesh.MeshSizeFactor', ms)
    points = []
    lines = []
    theta = 2*np.pi/n
    for pidx in range(n):
       x, y = pol2cart(r,pidx*theta)
       points.append((x,y,0))

    polygon = geom.add_polygon(points)
    geom.translate(polygon, (0,0,offset))
    prism = geom.extrude(polygon, (0,0,-T))
    mesh = geom.generate_mesh(dim=2)


fname = 'hex.stl'
mesh.write('hex.stl')

body = cpt.FloatingBody.from_file(fname)

body.keep_immersed_part()

hsd = hs.Hydrostatics(mm.Mesh(body.mesh.vertices, body.mesh.faces)).hs_data

m = hsd['disp_mass']
I = np.array([[hsd['Ixx'], -1*hsd['Ixy'], -1*hsd['Ixz']],
              [-1*hsd['Ixy'], hsd['Iyy'], -1*hsd['Iyz']],
              [-1*hsd['Ixz'], -1*hsd['Iyz'], hsd['Izz']]])
M = block_diag(m, m, m, I)
# body.mass = body.add_dofs_labels_to_matrix(M)

kHS = block_diag(0,0,hsd['stiffness_matrix'],0)
# body.hydrostatic_stiffness = body.add_dofs_labels_to_matrix(kHS)

omega0_estimate = np.sqrt(kHS[2,2]/M[2,2])
print(omega0_estimate)
```

**Comment by sharmi0** [comment]
Thank you @ryancoe ! I'm trying to generate heave added mass curves with the range of omegas. I don't really need 0.1-6, it's more like 0-2 rads because that's where the most "action" is when looking at the main wave spectra. This mesh was a test for a more complex mesh that I don't think can be created using pymsh or gmsh. How would you recommend going about acquiring a heave added mass plot for that? 
The biggest problem is that the mesh itself is too big (in terms of data). I don't think it matters how many frequencies I'm computing for. I get the resolution error anyway because the mesh is not fine enough; solidworks doesn't allow for a finer setting and my RAM does not have enough memory for it. 

I have some additional questions about the code: 
1)
`hsd = hs.Hydrostatics(mm.Mesh(body.mesh.vertices, body.mesh.faces)).hs_data`
Is this line getting you the inertia matrix of the object? And if so how are you deciding whether the values should be positive or negative in the inertia matrix, I ?

2)
Similar question with the mass. Are you setting the mass as some value or is meshmagick giving you that value (and if so where is that value coming from?)

**Comment by ryancoe** [comment]
@sharmi0 - It sounds like you agree that you can reduce the frequency range to match the wave spectrum. I want to re-emphasize that you can also consider that the frequency range should match the hydrodynamics of the body -- at high frequencies, a body of that size cannot respond. I suspect that when you consider this, you can find a mesh resolution that fits in memory. I also believe you may want to reconsider the `solver` you're using, as I believe the direct method is the most computationally intensive (https://ancell.in/capytaine/latest/user_manual/resolution.html#settings-of-the-solver) -- @mancellin may be able to give a more info on this. It looks like you can also consider setting `matrix_cache_size=0` to reduce memory usage. Again, I generally suspect that you can best avoid these memory issues entirely by making sure the body size, mesh size, and frequency range are all reasonable/in sync.

To your specific questions:

1. `hsd` is the hydrostatics data object produced by `Meshmagick`. It contains the inertial properties (assuming constant density) and hydrostatic properties. The signs of the inertia matrix `I` are based on the description given here: https://lheea.github.io/meshmagick/command_line/cli_usage.html#getting-inertial-properties-of-the-mesh
2. I am setting the mass properties based on `Meshmagick`, which is calculating these based on the center of gravity (which is (0,0,0) since I did not set it), the assumption that the body has a constant density, and the body being neutrally buoyant.

**Comment by mancellin** [comment]
I am also surprised that you have RAM issue for this relatively simple body. Wavelength that are too small to be resolved with a reasonable number of panels are probably irrelevant.

> I believe the direct method is the most computationally intensive

It is a little bit more intensive, but it should not make a big difference.
If you really need a high number of panels, the best strategy to limit the RAM usage would be to use the H-matrices as described in #51, but it is still experimental and requires some manual tuning.

**Comment by RubendeBruin** [comment]
What is the true size of the object? The length of one of the edges is 1260. Is that m (floating city), mm (building blocks for something bigger)?

![image](https://user-images.githubusercontent.com/34062862/116800768-a208c700-ab36-11eb-8cbf-7c68fc700356.png)

**Comment by sharmi0** [comment]
All of these comments were very helpful!
1) @ryancoe Graphing the body from 0-0.35 rads which are values around 0.22 rads didn't give me resolution errors because it was around the frequency range that matched the hydrodynamics of the body as you said. Thank you so much!
If I wanted to run a more complicated mesh - one that I don't think I can just create using the geometric properties included in pymsh or gmsh, can I just input the file as a floating body? Do I have to make any changes to the inertia matrix or does meshmagick take care of all that? Thank you!

2) @mancellin Thanks for the comment! I am able to avoid using as much RAM with the advice from ryan but I will keep this in mind.

3) @RubendeBruin The diameter of the hexagon is 2.20m and the height is 0.30m.

**Comment by ryancoe** [comment]
@sharmi0 - As @RubendeBruin hinted, there's been a misinterpretation of your geometry. My script above models the body with a diameter of 2 km. STL files can use different units, yours uses mm, but `capytaine` is interpreting it as m.

**Comment by sharmi0** [comment]
I changed the value of the diameter and the draft to the size I wanted and it is giving me 5.1rads as the heave natural frequency.
Does the body.show() function show everything in meters? 
![image](https://user-images.githubusercontent.com/80690027/117135237-aa4e4580-ad74-11eb-9caa-e914f00896a7.png)

I also wanted to retiterate my previous question:
If I wanted to run a more complicated mesh - one that I don't think I can just create using the geometric properties included in pymsh or gmsh, can I just input the file as a floating body mesh? Do I have to make any changes to the inertia matrix or does meshmagick take care of all that?

**Comment by ryancoe** [comment]
Yes `body.show()` dimensions are meters.

Yes, you can use an STL file to instantiate a `FloatingBody` object and then do the same Meshmagick steps to get the inertia matrix:

```python
body = cpt.FloatingBody.from_file('mystlfile.stl')
body.keep_immersed_part()
hsd = hs.Hydrostatics(mm.Mesh(body.mesh.vertices, body.mesh.faces)).hs_data
...
```

**Comment by sharmi0** [comment]
Hi,
I want to obtain a plot for the heave RAO of my object. I was playing around with the RAO example from the animation example. When I print `dataset['RAO']` I get a list of 6 complex numbers in a list (along with other information). Are these RAO values for different DOFs? What is the best way to get a value for just the heave rao for different frequencies? If I use this line:
`problems = [cpt.RadiationProblem(omega=omega, body=boat, radiating_dof="Heave"])` I get nan for all 6 values. 
Alternatively could I take the magnitude of the heave (3rd) value in the last of numbers I get when printing `dataset['RAO']`?

[hydrodynamics_5_16.zip](https://github.com/mancellin/capytaine/files/6489704/hydrodynamics_5_16.zip)

**Comment by mancellin** [comment]
> Are these RAO values for different DOFs?

Yes, they are the components of the RAO corresponding to each of the dofs.

> Alternatively could I take the magnitude of the heave (3rd) value in the last of numbers I get when printing dataset['RAO']?

In general, the vertical motion in waves of a body with 6 dofs is different from the vertical motion of a body with a single dof. So no, you should not do that.

Instead, define your body with only the dof(s) that you want.
For instance, replace
```
boat.add_all_rigid_body_dofs()
```
by
```
boat.add_translation_dof(name="Heave")
```

> I get nan for all 6 values

I guess the code is trying to compute the RAO of a body with 6 dofs but it is missing numerical values about 5 of them.

**Comment by sharmi0** [comment]
That makes sense, thanks! But how do I continue to use the mass matrix and other matrices like the hydro coefficients while analyzing one DOF. This line in the code `boat.mass = boat.add_dofs_labels_to_matrix(M)` gives me this error:
"conflicting sizes for dimension 'influenced_dof': length 6 on the data but length 1 on coordinate 'influenced_dof'"

**Comment by mancellin** [comment]
In Ryan's example, the hydrostatics matrices M and kHs are defined for a 6-dof body. I believe you can just pick the lines and columns of the dofs you want to keep. For a heaving only body, you'll then have a 1x1 matrix.

**Comment by ryancoe** [comment]
I have done something like this where I define a `FloatingBody` with all six DOFs (including defining the stiffness and mass), then I call `fb.keep_only_dofs(['Heave'])` to reduce it down to one before running the BEM, etc.

**Comment by sharmi0** [comment]
I tried that before, but that still gives me a dimension error "different number of dimensions on data and dims: 0 vs 2". 
Additionally, some RAOs (eg pitch), require coupled coefficients so how would capytaine produce results if I only put in one value from the hydro, mass matrices? Thanks!

**Comment by mancellin** [comment]
I'm not sure to understand what you mean. If you assume your body has only one degree of freedom which is heave, you won't have any pitch in your RAO.

**Comment by sharmi0** [comment]
Sorry I was just giving an example. What I meant was if my degree of freedom is pitch, the formula for the excitation force which is used to solve for RAO has coupled coefficients. So I was wondering how capytaine would solve the RAO for pitch if I'm only allowed to input one coefficient. 

I've attached a zip file of what I have currently. This example is for heave and I'm having issues with the dimensions of the matrices matching. 

I had another question. Is there a function to solve for excitation force in capytaine? 
[PEARL_sharmi.zip](https://github.com/mancellin/capytaine/files/6535107/PEARL_sharmi.zip)

**Comment by lottevandongen** [comment]
Dear all,

I had a question on the computation of the RAO as well. When I try
`dataset = cpt.assemble_dataset(results)
dataset['RAO'] = cpt.post_pro.rao(dataset, wave_direction=0)`

I get the error 

`
  File "C:\Programs\Anaconda3\envs\py37\lib\site-packages\capytaine\post_pro\rao.py", line 66, in rao
    X = np.linalg.solve(A, excitation)

  File "<__array_function__ internals>", line 6, in solve

  File "C:\Programs\Anaconda3\envs\py37\lib\site-packages\numpy\linalg\linalg.py", line 394, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)

TypeError: No loop matching the specified signature and casting was found for ufunc solve1`

Do you have a suggestion for trying to fix this problem? When running the example file 'Animation of the RAO' everything goes fine..

**Comment by mancellin** [comment]
From the error message, there seems to be something wrong with the type of data stored in `dataset`. Could you share the output of `print(dataset)`?

**Comment by lottevandongen** [comment]
Of course, this is the output of dataset:

`<xarray.Dataset>
Dimensions:                (influenced_dof: 6, omega: 1, radiating_dof: 6, wave_direction: 1)
Coordinates:
    g                      float64 9.81
    rho                    float64 1e+03
    body_name              <U31 'rectangular_parallelepiped_1412'
    water_depth            float64 24.0
  * omega                  (omega) float64 0.6283
  * radiating_dof          (radiating_dof) object 'Surge' 'Sway' ... 'Yaw'
  * influenced_dof         (influenced_dof) object 'Surge' 'Sway' ... 'Yaw'
  * wave_direction         (wave_direction) float64 0.0
Data variables:
    added_mass             (omega, radiating_dof, influenced_dof) float64 1.9...
    radiation_damping      (omega, radiating_dof, influenced_dof) float64 6.3...
    diffraction_force      (omega, wave_direction, influenced_dof) complex128 ...
    Froude_Krylov_force    (omega, wave_direction, influenced_dof) complex128 ...
    mass                   (influenced_dof, radiating_dof) object 3.756e+05 ....
    hydrostatic_stiffness  (influenced_dof, radiating_dof) object 0 0 0 ... 0 0
    excitation_force       (omega, wave_direction, influenced_dof) complex128 ...
Attributes:
    creation_of_dataset:        2021-06-14T10:24:26.502874
    incoming_waves_convention:  nemoh
    capytaine_version:          1.2 `

**Comment by mancellin** [comment]
The mass and hydrostatic stiffness variables are typed as generic "objects" and not as float or complex numbers. That might be the issue. How did you define them?

**Comment by lottevandongen** [comment]
Ah I found the problem, there were indeed 1x1 arrays within my matrices instead of float numbers. Thanks a lot!
