### ISSUE TITLE
setup fails on read-the-docs / pip

### ISSUE THREAD

**Issue by RubendeBruin** [mancellin/capytaine#76]
I'm trying to build the documentation for a package that requires capytaine. Howerver Read-the-Docs fails on the installation of capytaine with the following message:

```
Requirement already satisfied: sphinx>=3.2.1 in /home/docs/checkouts/readthedocs.org/user_builds/mafredo/envs/latest/lib/python3.8/site-packages (from -r docs/requirements.txt (line 4)) (4.0.2)
Collecting numpy
  Downloading numpy-1.21.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Collecting xarray
  Downloading xarray-0.18.2-py3-none-any.whl (807 kB)
Collecting capytaine
  Downloading capytaine-1.2.1.tar.gz (99 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/docs/checkouts/readthedocs.org/user_builds/mafredo/envs/latest/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qid58y49/capytaine_1bb6c27ac5274da7b470d0659e142576/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qid58y49/capytaine_1bb6c27ac5274da7b470d0659e142576/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ylbc1quq
         cwd: /tmp/pip-install-qid58y49/capytaine_1bb6c27ac5274da7b470d0659e142576/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qid58y49/capytaine_1bb6c27ac5274da7b470d0659e142576/setup.py", line 5, in <module>
        from numpy.distutils.core import Extension, setup
    ModuleNotFoundError: No module named 'numpy'
```

Could it be that capytaine setup is missing some requirements?

**Comment by mancellin** [comment]
Capytaine's setup.py requires numpy because of the Fortran extensions.

I'm not familiar with Read-the-docs. Is there a way to tell it to first complete the installation of Numpy before trying to install Capytaine? Something like replacing
```
pip install numpy capytaine
```
by
```
pip install numpy
pip install capytaine
```

**Comment by RubendeBruin** [comment]
Hi @mancellin, as far as I can see numpy is downloaded before capytaine. So I don't really understand where the error message comes from. I'm more familiar with conda myself.

Maybe there is an "install-requires" section in the requirements? 

ps:
For now I have just removed capyaine from the requirements and enclosed the example where I used in a try/except block. That way at least the docs build: https://mafredo.readthedocs.io/en/latest/auto_gallery/plot_extrapolation.html#sphx-glr-auto-gallery-plot-extrapolation-py

**Comment by mancellin** [comment]
> I'm more familiar with conda myself.

Me too and the installation with pip is second-tier right now.
I won't have time to delve into that for a while. In the mean time, leaving Capytaine as an optional dependency (if you can) is the best option.

Even if we fix the Numpy issue, Read-the-docs will need a Fortran compiler to complete the installation of Capytaine with pip.

**Comment by RubendeBruin** [comment]
Fair points. With the read-the-docs work-around working I'll close this issue

**Comment by mancellin** [comment]
FYI, there is now a precompiled pip package, so the work-around might not be necessary anymore.
