### ISSUE TITLE
Bemio -> Capytaine

### ISSUE THREAD

**Issue by ryancoe** [mancellin/capytaine#77]
I really like the `xarray` `Dataset` format used by `captyaine`. While as reported in #15, we can go from `capytaine` to `bemio`, it would be great to go the other direction too.

**Comment by ryancoe** [comment]
@michaelcdevin - you're working on this for a separate, but related project. Maybe you can submit a PR and @mancellin can decide whether this should be added to `capytaine` as a utility?

**Comment by michaelcdevin** [comment]
Will do, once I'm happy with the Bemio -> Capytaine functionality I'll submit a PR.
