### ISSUE TITLE
Minor tutorial errors

### ISSUE THREAD

**Issue by harpolea** [mancellin/capytaine#8]
I've been working through the tutorial and cookbook and come across a few minor errors:
- In the 'Defining linear potential flow problems' section of the tutorial, a RadiationProblem is set up. One of the arguments in the constructor is set to `sea_bottom=-np.infty`, however there is not an instruction prior to this section to `import numpy as np`. 
- In the 'Animation of the RAO' section of the cookbook, the code requires the file "boat_200.mar". I see that this is in the `docs/user_manual/examples/` directory in the repo, however it's not in the package installed via conda. You might want to have some instructions in the cookbook telling the user to download this file before running that example in the case that they have - like me - installed the package via conda rather than cloned the repo?
- When I tried running the final example 'Plot the influence matrix', I encountered the following error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-9f19a24d00d1> in <module>()
     11 # Plot the absolute value of the matrix V
     12 #
---> 13 plt.imshow(abs(S))
     14 plt.colorbar()
     15 plt.title("$|S|$")

TypeError: bad operand type for abs(): 'BlockMatrix'
```

**Comment by mancellin** [comment]
Good points. Thank you!
The issues are fixed in the `develop` branch and the new version will be published in the next days.
