### ISSUE TITLE
Contibuting guidelines

### ISSUE THREAD

**Issue by harpolea** [mancellin/capytaine#9]
It would be good if the contributing guidelines were outlined in e.g. a `CONTRIBUTING` file (see https://help.github.com/en/articles/setting-guidelines-for-repository-contributors for suggestions, and https://github.com/opengovernment/opengovernment/blob/master/CONTRIBUTING.md for an example of such a file)

**Comment by mancellin** [comment]
Done. Thank you for the suggestion.
